export const ADD_PROJECT = 'ADD_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const LOAD_PROJECTS_START = 'LOAD_PROJECTS_START';
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';
export const LOAD_PROJECTS_FAIL = 'LOAD_PROJECTS_FAIL';

export const ADD_BLOG = 'ADD_BLOG';
export const EDIT_BLOG = 'EDIT_BLOG';
export const DELETE_BLOG = 'DELETE_BLOG';
export const LOAD_BLOGS_START = 'LOAD_BLOGS_START';
export const LOAD_BLOGS_SUCCESS = 'LOAD_BLOGS_SUCCESS';
export const LOAD_BLOGS_FAIL = 'LOAD_BLOGS_FAIL';

export const ADD_TRANSLATION_ARABIC = 'ADD_TRANSLATION_ARABIC';
export const EDIT_TRANSLATION_ARABIC = 'EDIT_TRANSLATION_ARABIC';
export const LOAD_TRANSLATIONS_ARABIC_START = 'LOAD_TRANSLATIONS_ARABIC_START';
export const LOAD_TRANSLATIONS_ARABIC_SUCCESS = 'LOAD_TRANSLATIONS_ARABIC_SUCCESS';
export const LOAD_TRANSLATIONS_ARABIC_FAIL = 'LOAD_TRANSLATIONS_ARABIC_FAIL';
